### ISSUE TITLE
Why doesn't it create notifications on mobile?

### ISSUE THREAD

**Issue by QuentinPotgieter** [dennisbruner/vue-native-notification#3]
It works great on Desktop, but not at all on Mobile. Why doesn't it create notifications on mobile?

**Comment by dennisbruner** [comment]
Thats because mobile notifications require a registered service worker but this module does not register one... yet. I might look into it.

You can register a service worker yourself if you need mobile push notifications:
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

**Comment by QuentinPotgieter** [comment]
Thank you. It would be great if you can. Vuetify PWA already registers a service-worker.js file. It would be convenient to just add on to that.
