### ISSUE TITLE
Uglify in webpack is giving 'UglifyJs Name expected'

### ISSUE THREAD

**Issue by soechun** [dennisbruner/vue-native-notification#4]
Hi, 
I was trying to use this package and when i try to use webpack and uglify, it is giving the following error
```ERROR in static/js/vendor.f6f1f5df4149a9b9a4d2.js from UglifyJs
Name expected [./node_modules/vue-native-notification/index.js:47,0]
```
Any idea how to resolve this problem?  
Thank you

**Comment by dennisbruner** [comment]
I just tested using this module in webpack. Here are some things you can try:

 - Make sure you use the latest Node.js LTS version or newer. (`>=8.11.1`)
 - Your error may be caused by a wrong webpack configuration. Try using the default template you can get via vue-cli. (`vue init webpack project-name`)

This should fix your problem :)

**Comment by LouisMazel** [comment]
Hi,

With Node 8.11.3 (last stable version), my build failed with the same error...
